spring.datasource.url=jdbc:postgresql://localhost:5432/my_database
spring.datasource.username=my_database
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
myapp.token=8388542227:AAGETG-NwIUkL4vbW8tgABVFoJ7EN6N-lfg
spring.mail.host=smtp.example.com
spring.mail.port=587
spring.mail.username=your-email@example.com
spring.mail.password=your-email-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true